"use client";

import dynamic from "next/dynamic";

const loading = () => <p className="empty">불러오는 중…</p>;

export const InfraTab = dynamic(() => import("@/components/InfraTab"), { loading });
export const EsgRegTab = dynamic(() => import("@/components/EsgRegTab"), { loading });
export const GreenMineralsTab = dynamic(() => import("@/components/GreenMineralsTab"), { loading });
export const BookClubTab = dynamic(() => import("@/components/BookClubTab"), { loading });
export const EducationTab = dynamic(() => import("@/components/EducationTab"), { loading });
export const ResearchTab = dynamic(() => import("@/components/ResearchTab"), { loading });
export const CardNewsTab = dynamic(() => import("@/components/CardNewsTab"), { loading });
export const ChartTradeTab = dynamic(() => import("@/components/ChartTradeTab"), { loading });
export const EventStudyTab = dynamic(() => import("@/components/EventStudyTab"), { loading });
export const EsgThemesTab = dynamic(() => import("@/components/EsgThemesTab"), { loading });
export const EtfHoldingsTab = dynamic(() => import("@/components/EtfHoldingsTab"), { loading });
export const EtfKor15Tab = dynamic(() => import("@/components/EtfKor15Tab"), { loading });
export const EtfNewTab = dynamic(() => import("@/components/EtfNewTab"), { loading });
export const EtfSupplyPanel = dynamic(() => import("@/components/EtfSupplyPanel"), { loading });
export const EtfWeightMonitorTab = dynamic(() => import("@/components/EtfWeightMonitorTab"), { loading });
export const KosdaqActiveTab = dynamic(() => import("@/components/KosdaqActiveTab"), { loading });
export const CountryEtfTab = dynamic(() => import("@/components/CountryEtfTab"), { loading });
export const GeoTab = dynamic(() => import("@/components/GeoTab"), { loading });
export const KrMarketTab = dynamic(() => import("@/components/KrMarketTab"), { loading });
export const LeverageEtfTab = dynamic(() => import("@/components/LeverageEtfTab"), { loading });
export const MacroTab = dynamic(() => import("@/components/MacroTab"), { loading });
export const YenCarryTab = dynamic(() => import("@/components/YenCarryTab"), { loading });
export const CftcTab = dynamic(() => import("@/components/CftcTab"), { loading });
export const PreciousMetalsTab = dynamic(() => import("@/components/PreciousMetalsTab"), { loading });
export const CryptoAssetsTab = dynamic(() => import("@/components/CryptoAssetsTab"), { loading });
export const VolatilityMonitorTab = dynamic(() => import("@/components/VolatilityMonitorTab"), { loading });
export const DerivativesTab = dynamic(() => import("@/components/DerivativesTab"), { loading });
export const MarketGammaTab = dynamic(() => import("@/components/MarketGammaTab"), { loading });
export const QuantTab = dynamic(() => import("@/components/QuantTab"), { loading });
export const TradingIdeasTab = dynamic(() => import("@/components/TradingIdeasTab"), { loading });
export const WeightOptimizeTab = dynamic(() => import("@/components/WeightOptimizeTab"), { loading });
export const NlpPulseTab = dynamic(() => import("@/components/NlpPulseTab"), { loading });
export const GraphTab = dynamic(() => import("@/components/GraphTab"), { loading });
export const WallStreetGurusTab = dynamic(() => import("@/components/WallStreetGurusTab"), { loading });
export const TradingSignalsTab = dynamic(() => import("@/components/TradingSignalsTab"), { loading });
export const MoneyFlowTab = dynamic(() => import("@/components/MoneyFlowTab"), { loading });
export const SimulateTab = dynamic(() => import("@/components/SimulateTab"), { loading });
export const UsPortfolioTab = dynamic(() => import("@/components/UsPortfolioTab"), { loading });
export const AiPortTab = dynamic(() => import("@/components/AiPortTab"), { loading });
export const CorridorTab = dynamic(() => import("@/components/CorridorTab"), { loading });
export const UsMarketTab = dynamic(() => import("@/components/UsMarketTab"), { loading });
export const UsMidtermTab = dynamic(() => import("@/components/UsMidtermTab"), { loading });
export const MidtermStudyTab = dynamic(() => import("@/components/MidtermStudyTab"), { loading });
export const PoliThemesTab = dynamic(() => import("@/components/PoliThemesTab"), { loading });
export const ThemeEtfTab = dynamic(() => import("@/components/ThemeEtfTab"), { loading });
export const AiEtfTab = dynamic(() => import("@/components/AiEtfTab"), { loading });
export const EtfDbTab = dynamic(() => import("@/components/EtfDbTab"), { loading });
export const EtfDbUsTab = dynamic(() => import("@/components/EtfDbUsTab"), { loading });
